namespace PicNetStudio.Avalonia.PicNet;

public enum SKDrawType {
    Color,
    Line,
    Paint,
    Region,
    Rect,
    RoundRect,
    Oval,
    Circle,
    Path,
    Points,
    Point,
    Image,
    Picture,
    Drawable,
    Bitmap,
    Surface,
    Text,
    PositionedText,
    TextOnPath,
    Annotation,
    UrlAnnotation,
    NamedDestinationAnnotation,
    LinkDestinationAnnotation,
    BitmapNinePatch,
    ImageNinePatch,
    BitmapLattice,
    ImageLattice,
    Vertices,
    Arc,
    RoundRectDifference,
    Atlas,
    Patch
}